# Generated by Django 5.2.3 on 2025-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100)),
                ('modell', models.CharField(max_length=100)),
                ('baujahr', models.PositiveIntegerField()),
                ('farbe', models.CharField(max_length=50)),
                ('kilometer', models.PositiveIntegerField()),
                ('unfallhistorie', models.CharField(choices=[('keine', 'Keine'), ('ja', 'Ja')], max_length=10)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kraftstoffart', models.CharField(choices=[('benzin', 'Benzin'), ('diesel', 'Diesel')], max_length=10)),
                ('getriebe', models.CharField(choices=[('manuell', 'Manuell'), ('automatik', 'Automatik')], max_length=10)),
                ('au_hu', models.DateField()),
                ('leistung', models.PositiveIntegerField(help_text='kW')),
                ('gewicht', models.PositiveIntegerField(help_text='kg')),
                ('hubraum', models.PositiveIntegerField(help_text='ccm')),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('ausstattung', models.JSONField(blank=True, default=list)),
                ('extras', models.JSONField(blank=True, default=list)),
                ('sonstigeMerkmale', models.TextField(blank=True)),
                ('dateien', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
