# Generated by Django 5.2.3 on 2025-07-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_car_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='dateien',
        ),
        migrations.AlterField(
            model_name='car',
            name='ausstattung',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='car',
            name='extras',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='car',
            name='gewicht',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='hubraum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='leistung',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='preis',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='unfallhistorie',
            field=models.CharField(choices=[('keine', 'Keine'), ('ja', 'Ja')], max_length=5),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/%Y/%m/%d/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garage.car')),
            ],
        ),
    ]
